### ISSUE TITLE
总是报这2个错误！

### ISSUE THREAD

**Issue by czy2022** [SaulGoodManC99/TelegramQueryIDFetcher#6]
C:\Users\AAA\Desktop\TelegramQueryIDFetcher-main>python auto_get_token.py
Traceback (most recent call last):
  File "C:\Users\AAA\Desktop\TelegramQueryIDFetcher-main\auto_get_token.py", line 18, in <module>
    from bot.utils.logger import logger
  File "C:\Users\AAA\Desktop\TelegramQueryIDFetcher-main\bot\utils\logger.py", line 2, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'  

总是报这2个错误！

**Comment by czy2022** [comment]
![360截图20241011174844](https://github.com/user-attachments/assets/7198bcd1-088a-4441-b245-f2af97abd457)

**Comment by SaulGoodManC99** [comment]
pip install loguru
我忘了在req加库了，或者git pull更新
我修复了这个问题
